esphome:
  name: diverter
  platform: ESP8266
  board: esp01_1m
  
external_components:
  # equivalent shorthand for GitHub
  #- source: github://esphome/esphome@dev
  #  components: [ rtttl ]

  # use all components from a local folder
  - source:
      type: local
      path: custom_components      

wifi:
  ssid: Cao_que_ladra
  password: Tenho um gato.
captive_portal:


ota:

web_server:
  port: 80
  
i2c:
  sda: GPIO12
  scl: GPIO14
  frequency: 400kHz

#logger:
#  level: DEBUG

sensor:
  - platform: diverter
    voltage:
      name: Voltage
    current_a:
      name: Current
    active_power_a:
      name: Active Power
    energy_buffer:
      name: Energy Buffer Count
    energy_diverted:
      name: Diversion Cycles
    diverter_parameters:
      energy_buffer_size: 360 #default 3600J=1Wh
      energy_threshold_high: 50% #default 75%
      energy_threshold_low: 50% #default 25%
    #update_interval: 5s #default 60s

  # NTC Temperature
  - platform: ntc
    sensor: temp_resistance_reading
    name: Temperature
    unit_of_measurement: "°C"
    accuracy_decimals: 1
    icon: "mdi:thermometer"
    calibration:
      b_constant: 3350
      reference_resistance: 10kOhm
      reference_temperature: 298.15K
  - platform: resistance
    id: temp_resistance_reading
    sensor: temp_analog_reading
    configuration: DOWNSTREAM
    resistor: 32kOhm
  - platform: adc
    id: temp_analog_reading
    pin: A0

status_led:
  pin:
    number: GPIO0
    inverted: yes

